-- Inventory business data is accessible only through authorized server routes. No data changes.
ALTER TABLE public.import_batches ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.import_batches FROM PUBLIC, anon, authenticated;
ALTER TABLE public.import_batch_rows ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.import_batch_rows FROM PUBLIC, anon, authenticated;
ALTER TABLE public.stock_adjustments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.stock_adjustments FROM PUBLIC, anon, authenticated;
ALTER TABLE public.item_family_links ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.item_family_links FROM PUBLIC, anon, authenticated;
ALTER TABLE public.daily_fg_sales_import ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.daily_fg_sales_import FROM PUBLIC, anon, authenticated;
ALTER TABLE public.item_families ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.item_families FROM PUBLIC, anon, authenticated;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.items FROM PUBLIC, anon, authenticated;
ALTER TABLE public.item_aliases ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.item_aliases FROM PUBLIC, anon, authenticated;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.suppliers FROM PUBLIC, anon, authenticated;
ALTER TABLE public.inward_entries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.inward_entries FROM PUBLIC, anon, authenticated;
ALTER TABLE public.bom_models ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.bom_models FROM PUBLIC, anon, authenticated;
ALTER TABLE public.bom_versions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.bom_versions FROM PUBLIC, anon, authenticated;
ALTER TABLE public.bom_lines ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.bom_lines FROM PUBLIC, anon, authenticated;
ALTER TABLE public.stock_reconciliations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.stock_reconciliations FROM PUBLIC, anon, authenticated;
ALTER VIEW public.v_item_lookup SET (security_invoker = true);
REVOKE ALL ON TABLE public.v_item_lookup FROM PUBLIC, anon, authenticated;
ALTER VIEW public.v_inward_summary SET (security_invoker = true);
REVOKE ALL ON TABLE public.v_inward_summary FROM PUBLIC, anon, authenticated;
ALTER FUNCTION public.set_updated_at() SET search_path = '';
ALTER FUNCTION public.update_updated_at_column() SET search_path = '';
REVOKE EXECUTE ON FUNCTION public.set_updated_at(), public.update_updated_at_column() FROM PUBLIC, anon, authenticated;
-- New application objects require explicit public-client grants.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
